/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package massas2;

import beans.Prod;
import dao.DaoProd;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fábio
 */
public class ADCitem extends javax.swing.JFrame {

    

    /**
     * Creates new form ADCitem
     */
    public ADCitem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NomeADC = new javax.swing.JTextField();
        ADCbutao = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        QuantADC = new javax.swing.JSpinner();
        ADCbutao1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adc Itens");
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NomeADC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeADCActionPerformed(evt);
            }
        });
        getContentPane().add(NomeADC, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 154, 122, -1));

        ADCbutao.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        ADCbutao.setText("CADASTRAR");
        ADCbutao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADCbutaoActionPerformed(evt);
            }
        });
        getContentPane().add(ADCbutao, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 255, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----------", "Ingredientes", "EPI", "Prod/Limpeza", "Ingredientes" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 109, 122, -1));

        jLabel9.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jLabel9.setText("Tipo do Item");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 106, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jLabel10.setText("Item");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 150, 66, -1));

        jLabel13.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jLabel13.setText("Quantidade");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 208, 133, -1));
        getContentPane().add(QuantADC, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 212, -1, -1));

        ADCbutao1.setBackground(new java.awt.Color(255, 153, 153));
        ADCbutao1.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        ADCbutao1.setText("VOLTAR");
        ADCbutao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADCbutao1ActionPerformed(evt);
            }
        });
        getContentPane().add(ADCbutao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 222, 196));

        jLabel14.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jLabel14.setText("Adicionar Item");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel14)
                .addContainerGap(143, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel14)
                .addContainerGap(254, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NomeADCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeADCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeADCActionPerformed

    private void ADCbutaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADCbutaoActionPerformed
        String tipo = jComboBox1.getSelectedItem().toString();
        String produto = NomeADC.getText();
        int quantidade = Integer.parseInt(QuantADC.getValue().toString());
        
        Prod prod = new Prod();
        prod.setTipo(tipo);
        prod.setProduto(produto);
        prod.setQuantidade(quantidade);
        
        DaoProd daoprod = new DaoProd();
        daoprod.inserir(prod);
        
        NomeADC.setText("");
        QuantADC.setValue(0);
        
        JOptionPane.showMessageDialog(null, "item realizado com sucesso!!");
    }//GEN-LAST:event_ADCbutaoActionPerformed

    private void ADCbutao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADCbutao1ActionPerformed
        // TODO add your handling code here:
        dispose();
        Telaprinc form = new Telaprinc();
        form.setVisible(true);
    }//GEN-LAST:event_ADCbutao1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADCitem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADCitem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADCitem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADCitem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADCitem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADCbutao;
    private javax.swing.JButton ADCbutao1;
    private javax.swing.JTextField NomeADC;
    private javax.swing.JSpinner QuantADC;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

   
        }
    
