/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package massas2;

import beans.Prod;
import dao.DaoProd;
import javax.swing.JOptionPane;

/**
 *
 * @author Fábio
 */
public class EditItem extends javax.swing.JFrame {

  
    
    
    public EditItem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ADCbutao1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        quanTxt = new javax.swing.JSpinner();
        editBTN = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        excluirBTN = new javax.swing.JButton();
        tipTxt = new javax.swing.JComboBox<>();
        codTET = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtProd1 = new javax.swing.JTextField();
        pesBnt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edição de Itens");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 222, 196));

        ADCbutao1.setBackground(new java.awt.Color(255, 153, 153));
        ADCbutao1.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        ADCbutao1.setText("VOLTAR");
        ADCbutao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADCbutao1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        jLabel6.setText("Quantidade");

        editBTN.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        editBTN.setText("Editar");
        editBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBTNActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        jLabel5.setText("Tipo");

        excluirBTN.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        excluirBTN.setText("Excluir");
        excluirBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirBTNActionPerformed(evt);
            }
        });

        tipTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        tipTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipTxtActionPerformed(evt);
            }
        });

        codTET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codTETActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        jLabel4.setText("Item");

        jLabel3.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        jLabel3.setText("ID");

        idTxt.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        jLabel7.setText("Edição e Exclusão de Itens");

        jLabel8.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        jLabel8.setText("Procurar item por ID");

        pesBnt.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        pesBnt.setText("Pesquisar");
        pesBnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesBntActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quanTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProd1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(160, 160, 160))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ADCbutao1)
                        .addGap(61, 61, 61)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel8)
                        .addGap(24, 24, 24)
                        .addComponent(codTET, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(pesBnt, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(editBTN)
                        .addGap(18, 18, 18)
                        .addComponent(excluirBTN)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ADCbutao1)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(codTET, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesBnt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtProd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tipTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quanTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(excluirBTN)
                    .addComponent(editBTN))
                .addGap(79, 79, 79))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 550, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void excluirBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirBTNActionPerformed
        // TODO add your handling code here:
        
        int id = Integer.parseInt(idTxt.getText());
        DaoProd daoprod = new DaoProd();
        daoprod.excluir(id);
        
        idTxt.setText("");
        tipTxt.setSelectedItem("");
        quanTxt.setValue("0");
        

        JOptionPane.showMessageDialog(null, "Exclusão realizada com sucesso!!");

        dispose();
    }//GEN-LAST:event_excluirBTNActionPerformed

    private void editBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBTNActionPerformed
        int id = Integer.parseInt(idTxt.getText());
        String produto = txtProd1.getText();
        String tip = tipTxt.getSelectedItem().toString();
        int quant = Integer.parseInt(quanTxt.getValue().toString());

        Prod prod_edit = new Prod();
        prod_edit.setId(id);
        prod_edit.setProduto(produto);
        prod_edit.setTipo(tip);
        prod_edit.setQuantidade(quant);

        DaoProd daoprod = new DaoProd();
        daoprod.editar(prod_edit);

        idTxt.setText("");
        txtProd1.setText("");
        tipTxt.setSelectedItem("");
        quanTxt.setValue("0");

        JOptionPane.showMessageDialog(null, "Edição realizada com sucesso!!");

        dispose();
    }//GEN-LAST:event_editBTNActionPerformed

    private void ADCbutao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADCbutao1ActionPerformed
        // TODO add your handling code her
        dispose();
        Telaprinc form = new Telaprinc();
        form.setVisible(true);
    }//GEN-LAST:event_ADCbutao1ActionPerformed

    private void tipTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipTxtActionPerformed

    private void codTETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codTETActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codTETActionPerformed

    private void pesBntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesBntActionPerformed
    int idPesquisa = Integer.parseInt(codTET.getText());
    DaoProd daoprod = new DaoProd();
    Prod prod = daoprod.getProd(idPesquisa);
    if (prod == null){
        JOptionPane.showMessageDialog(this,"item não encontrado");
}
    else{
        idTxt.setText(String.valueOf(prod.getId()));
        txtProd1.setText(prod.getProduto());
        tipTxt.setSelectedItem(prod.getTipo());
        quanTxt.setValue(prod.getQuantidade());
    }
            
    }//GEN-LAST:event_pesBntActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADCbutao1;
    private javax.swing.JTextField codTET;
    private javax.swing.JButton editBTN;
    private javax.swing.JButton excluirBTN;
    private javax.swing.JTextField idTxt;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton pesBnt;
    private javax.swing.JSpinner quanTxt;
    private javax.swing.JComboBox<String> tipTxt;
    private javax.swing.JTextField txtProd1;
    // End of variables declaration//GEN-END:variables
}
